# Generated by Django 4.1.12 on 2024-03-07 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='ezskedevent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ezskedevent',
            name='rank',
        ),
        migrations.AddField(
            model_name='ezskedevent',
            name='brief_time',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='ezskedevent',
            name='event_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='ezskedevent',
            name='event_type',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='ezskedevent',
            name='land_time',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='ezskedevent',
            name='remarks',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='ezskedevent',
            name='takeoff_time',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='ezskedevent',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='ezskedevent',
            name='sna',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='home.sna'),
        ),
    ]
