# Generated by Django 4.1.12 on 2024-03-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sna_remove_ezskedevent_name_remove_ezskedevent_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ezskedevent',
            name='crew_1',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='ezskedevent',
            name='crew_2',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
