# Generated by Django 4.1.12 on 2024-03-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ezskedevent_crew_1_ezskedevent_crew_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ezskedevent',
            name='brief_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='ezskedevent',
            name='land_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='ezskedevent',
            name='takeoff_time',
            field=models.TimeField(default=None),
        ),
    ]
