# Generated by Django 4.1.12 on 2024-03-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_ezskedevent_brief_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ezskedevent',
            name='remarks',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
