# Generated by Django 4.1.12 on 2024-03-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_ezskedevent_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ezskedevent',
            name='crew_2',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
