# Generated by Django 4.1.12 on 2024-03-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_ezskedevent_crew_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ezskedevent',
            name='takeoff_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
